apiVersion: v1
kind: Service
metadata:
  name: emulator
  namespace: rangemaster
  labels:
    app: emulator
spec:
  type: ClusterIP
  selector:
    app: emulator
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
