apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rangemaster

resources:
  - namespace.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - api-server/configmap.yaml
  - api-server/deployment.yaml
  - api-server/service.yaml
  - portal/deployment.yaml
  - portal/service.yaml
  - emulator/deployment.yaml
  - emulator/service.yaml
