idf_component_register(
    LDFRAGMENTS "esp32p4_bss_fix.lf"
    SRCS
        "main.cpp"
        "display/jd9365_panel.cpp"
        "display/gsl3680_touch.cpp"
        "store/game_store.cpp"
        "net/coprocessor.cpp"
        "net/http_sync.cpp"
        "ui/ui_manager.cpp"
        "ui/screen_dashboard.cpp"
        "ui/screen_start.cpp"
        "ui/screen_spiel.cpp"
        "ui/screen_resultate.cpp"
        "ui/screen_geschichte.cpp"
        "ui/screen_kredite.cpp"
        "ui/screen_einstellungen.cpp"
        "ui/screen_spiller.cpp"
        "ui/screen_wifi.cpp"
        "ui/screen_bluetooth.cpp"
        "lora_stub/lora_stub.cpp"
    INCLUDE_DIRS
        "."
        "display"
        "store"
        "net"
        "ui"
        "lora_stub"
    REQUIRES
        esp_lcd
        esp_lvgl_port
        lvgl
        driver
        esp_http_client
        mbedtls
        nvs_flash
        json
        esp_timer
        freertos
        log
        spi_flash
        esp_system
        esp_psram
)
